/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_open_filesel (void);
GtkWidget* create_window_constants (void);
GtkWidget* create_window_ccwf (void);
GtkWidget* create_window_jbord (void);
GtkWidget* create_save_filesel (void);
GtkWidget* create_window_nlab (void);
GtkWidget* create_window_about (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window_files (void);
GtkWidget* create_window_Rmatrix (void);
GtkWidget* create_window_eintervals (void);
GtkWidget* create_filechooserdialog1 (void);
