/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"


GtkWidget *main_window;
static void parse_command_line (GtkWidget *mw,
				int argc,
				char *argv[]);

gboolean GPRINT=FALSE;
gboolean FRESCO_IS_RUNNING=FALSE;

/* This is the filename of the file currently being edited. */
gchar *current_filename=NULL ;

static void usage (void);

/* Forward declarations for missing functions */
void create_popup(void);
gchar* glade_util_make_absolute_path(const gchar *directory, const gchar *filename);
void real_open_file(GtkWidget *widget, const gchar *filename);

gint
main (int argc, char *argv[])
{
  /*
  windows 1 declared as global, so this line must be omitted:
  GtkWidget *window1;*/
  GtkWidget *window_ccwf;
  GtkWidget *window_constants;
  GtkWidget *window_jbord;
  /*GtkWidget *window_bins;*/
  GtkWidget *window_Rmatrix;
  GtkWidget *window_files;
  
 

   guint context;
  GtkWidget *status;

  /*guint32 delay=10000;*/

  /* gtk_set_locale() removed in GTK-4 */
  gtk_init ();

  /*Resouce file - gtk_rc_parse removed in GTK-4, use CSS instead */
  /* gtk_rc_parse("xfresco.rc"); */

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_window = create_main_window ();

  /* This is automatically output by Glade to set the directories containing
     the pixmaps. The first directory is the place where pixmaps will be
     installed. The second directory is where the uninstalled pixmaps are,
     so the pixmaps can still be found without installing the application.
     Note that for Gnome applications, pixmaps are handled differently, and
     the pixmaps must be installed. PACKAGE_DATA_DIR and PACKAGE_SOURCE_DIR
     are set by configure.in and must appear in acconfig.h */
  /* PACKAGE_DATA_DIR not defined - commenting out for now */
  /* add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps"); */

  /* Commented in version 2.0 */
  /*   add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps"); */
	
  
  /*Dialog window with CCWF parameters*/
  window_ccwf=create_window_ccwf();

  window_constants=create_window_constants();
  window_jbord=create_window_jbord();
  /*window_bins=create_window_bins();*/
  window_Rmatrix=create_window_Rmatrix();
  window_files=create_window_files();
  

  g_object_set_data(G_OBJECT(main_window),
		      "window_ccwf",window_ccwf);
  g_object_set_data(G_OBJECT(main_window),
		      "window_constants",window_constants);
  g_object_set_data(G_OBJECT(main_window),
		    "window_jbord",window_jbord);
  /*g_object_set_data(G_OBJECT(main_window),
    "window_bins",window_bins);*/
  g_object_set_data(G_OBJECT(main_window),
		     "window_Rmatrix",window_Rmatrix);
  g_object_set_data(G_OBJECT(main_window),
		     "window_files",window_files);

  status=lookup_widget(main_window,"statusbar");
  context=gtk_statusbar_get_context_id(GTK_STATUSBAR(status),
				       "main");
  gtk_statusbar_push( GTK_STATUSBAR(status), context,"OK");

  /*Some extra signals that I don't know how to include with glade */
  /*  add_extra_signals(main_window);*/

  /* Attach popup menu to clists */
  create_popup();

  gtk_widget_show (main_window);

  parse_command_line (main_window,argc, argv);




  /*
  gtk_timeout_add(delay,
                  timeout_callback,
                  main_window);
		  */


  /* GTK-4 main loop replacement */
  while (g_list_model_get_n_items(gtk_window_get_toplevels()) > 0)
    g_main_context_iteration(NULL, TRUE);

  return 0;
}



/* This has been "borrowed" from glade file "main.c"
 * 
 */
static void
parse_command_line (GtkWidget *mw,int argc, gchar *argv[])
{
 
  gint i;

  /* This doesn't work with Gnome, so we set argc to 1 to skip it.
     I think we have to use popt for Gnome. */
#ifdef USE_GNOME
  argc = 1;
#endif


     for (i = 1; i < argc; i++)
    {
      if (!argv[i]) continue;
      if (!strcmp (argv[i], "-s") || !strcmp (argv[i], "--silence"))
	GPRINT = FALSE;
      else if (!strcmp (argv[i], "-v") || !strcmp (argv[i], "--verbose"))
	GPRINT = TRUE;
      else if (!strcmp (argv[i], "-h") || !strcmp (argv[i], "--help"))
	usage();
      else if (argv[i]){
	/*filename = (gchar*) argv[i];*/
	/*ilename = g_strdup(argv[i]);*/
	gchar *directory= g_get_current_dir ();
	gchar *filename = glade_util_make_absolute_path (directory,argv[i]);
	real_open_file(mw,filename);
	current_filename=g_strdup(filename);
	g_free (directory);
	g_free (filename);
      } 	
      else
	usage ();
    }



/*   if (filename) */
/*     { */
/*       directory = g_get_current_dir (); */
/*       filename = glade_util_make_absolute_path (directory, filename); */
/*       g_print("Before real_open_file filename=%s\n",filename); */
/*       real_open_file(mw,filename); */
/*       current_filename=g_strdup(filename); */
/*       g_free (directory); */
/*       g_free (filename); */
/*     } */
}


static void
usage (void)
{
  fprintf (stderr, "Usage: xfresco [-s|--silence] [<filename>]\n");
  fprintf (stderr, "\t -s|--silence: No trace output on stdout\n");
  fprintf (stderr, "\t -v|--verbose: Trace output on stdout\n");
  fprintf (stderr, "\t <filename>: fresco input file to load\n");
  exit (0);
}





/* int */
/* main (int argc, char *argv[]) */
/* { */
/*   GtkWidget *main_window; */
/*   GtkWidget *open_filesel; */
/*   GtkWidget *window_constants; */
/*   GtkWidget *window_ccwf; */
/*   GtkWidget *window_jbord; */
/*   GtkWidget *save_filesel; */
/*   GtkWidget *window_nlab; */
/*   GtkWidget *window_about; */
/*   GtkWidget *window2; */
/*   GtkWidget *window_files; */
/*   GtkWidget *window_Rmatrix; */
/*   GtkWidget *window_eintervals; */

/* /\* #ifdef ENABLE_NLS *\/ */
/* /\*   bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR); *\/ */
/* /\*   bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8"); *\/ */
/* /\*   textdomain (GETTEXT_PACKAGE); *\/ */
/* /\* #endif *\/ */

/*   gtk_set_locale (); */
/*   gtk_init (&argc, &argv); */

/*   add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps"); */

/*   /\* */
/*    * The following code was added by Glade to create one of each component */
/*    * (except popup menus), just so that you see something after building */
/*    * the project. Delete any components that you don't want shown initially. */
/*    *\/ */
/*   main_window = create_main_window (); */
/*   gtk_widget_show (main_window); */
/*   open_filesel = create_open_filesel (); */
/*   gtk_widget_show (open_filesel); */
/*   window_constants = create_window_constants (); */
/*   gtk_widget_show (window_constants); */
/*   window_ccwf = create_window_ccwf (); */
/*   gtk_widget_show (window_ccwf); */
/*   window_jbord = create_window_jbord (); */
/*   gtk_widget_show (window_jbord); */
/*   save_filesel = create_save_filesel (); */
/*   gtk_widget_show (save_filesel); */
/*   window_nlab = create_window_nlab (); */
/*   gtk_widget_show (window_nlab); */
/*   window_about = create_window_about (); */
/*   gtk_widget_show (window_about); */
/*   window2 = create_window2 (); */
/*   gtk_widget_show (window2); */
/*   window_files = create_window_files (); */
/*   gtk_widget_show (window_files); */
/*   window_Rmatrix = create_window_Rmatrix (); */
/*   gtk_widget_show (window_Rmatrix); */
/*   window_eintervals = create_window_eintervals (); */
/*   gtk_widget_show (window_eintervals); */

/*   gtk_main (); */
/*   return 0; */
/* } */

